
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iklirbbiyumwofjyslqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrbGlyYmJpeXVtd29manlzbHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjQ3OTQsImV4cCI6MjA2MjIwMDc5NH0.Ke53JpEegh1CwZjtvZsGzxyyNuCgdk1DZHtD8S_5c1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-application-name': 'IncomeProperty',
    },
  },
});
